using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;
using FluentAssertions;
using AgentMemory.Nams.Client;
using AgentMemory.Nams.Domain;

namespace AgentMemory.Tests.Integration.Nams;

/// <summary>
/// Live tests for the Phase 10f TCK Platinum conversation-lifecycle/context additions:
/// <see cref="INamsClient.ListConversationsAsync"/> and <see cref="INamsClient.GetObservationsAsync"/>. See
/// <c>docs/reviews/NAMS_Phase10f_ConversationLifecycleContext_PlanningAndImplementationPlan.md</c> for the live
/// probe that informed this design -- including a second, in-CI-adjacent attempt at a genuinely-asserted
/// "observations eventually appear" test that was removed after it actually failed on a 150s bound (25
/// messages), proving the worker's timing isn't reliably reproducible within a live-test-friendly budget. The
/// remaining test below only asserts the always-correct shape, deliberately not gambling on worker timing.
/// </summary>
[Collection("NAMS Live")]
[Trait("Category", "Integration")]
public sealed class NamsConversationLifecycleTests
{
    private readonly NamsLiveFixture _fixture;

    public NamsConversationLifecycleTests(NamsLiveFixture fixture) => _fixture = fixture;

    [LiveNamsFact]
    public async Task ListConversationsAsync_ReturnsCreatedConversationsWithCorrectSummaryFields()
    {
        var namsClient = _fixture.Services!.GetRequiredService<INamsClient>();
        var userIdA = UniqueUserId();
        var userIdB = UniqueUserId();

        var conversationA = await namsClient.CreateConversationAsync(
            userIdA, new Dictionary<string, string> { ["title"] = $"{userIdA}-title" }, CancellationToken.None);
        var conversationB = await namsClient.CreateConversationAsync(
            userIdB, new Dictionary<string, string> { ["title"] = $"{userIdB}-title" }, CancellationToken.None);

        try
        {
            var conversations = await namsClient.ListConversationsAsync(limit: 200, CancellationToken.None);

            var foundA = conversations.Should().ContainSingle(c => c.Id == conversationA.Id,
                "the conversation this test just created via CreateConversationAsync must appear in the list, " +
                "not just some arbitrary conversation").Which;
            foundA.UserId.Should().Be(userIdA);
            foundA.Title.Should().Be($"{userIdA}-title");
            foundA.MessageCount.Should().Be(0, "no messages were added to this conversation");

            var foundB = conversations.Should().ContainSingle(c => c.Id == conversationB.Id).Which;
            foundB.UserId.Should().Be(userIdB);
            foundB.Title.Should().Be($"{userIdB}-title");
        }
        finally
        {
            await namsClient.DeleteConversationAsync(conversationA.Id, CancellationToken.None);
            await namsClient.DeleteConversationAsync(conversationB.Id, CancellationToken.None);
        }
    }

    [LiveNamsFact]
    public async Task GetObservationsAsync_OnFreshConversation_ReturnsEmptyTypedList()
    {
        var namsClient = _fixture.Services!.GetRequiredService<INamsClient>();
        var conversation = await namsClient.CreateConversationAsync(UniqueUserId(), null, CancellationToken.None);

        try
        {
            await namsClient.AddMessagesAsync(
                conversation.Id,
                [new NamsMessageInput("A single message -- not enough to trigger observation generation.", "user")],
                CancellationToken.None);

            var observations = await namsClient.GetObservationsAsync(conversation.Id, limit: 50, CancellationToken.None);

            observations.Should().NotBeNull().And.BeEmpty(
                "observations are only generated by NAMS's server-side worker after a much larger message " +
                "window accumulates (confirmed empirically at ~20 messages) -- a single message must not " +
                "produce any");
        }
        finally
        {
            await namsClient.DeleteConversationAsync(conversation.Id, CancellationToken.None);
        }
    }

    // [CallerMemberName] embeds the calling test's name in UserId, matching the convention already established
    // by NamsLiveConnectivityTests.UniqueIdentity / NamsMultiInstanceMappingTests.UniqueIdentity -- aids tracing
    // any conversation that outlives its test (e.g. a failed assertion skipping the try/finally cleanup).
    private static string UniqueUserId([CallerMemberName] string testName = "") =>
        $"test-{testName}-{Guid.NewGuid():N}";
}
