namespace AgentMemory.Core.Memory;

/// <summary>
/// The reviewed <c>canonical → surface forms</c> table behind <see cref="MemoryRelationLexicon"/>.
/// </summary>
/// <remarks>
/// <para>
/// Authored in one direction only. The lookup index is derived at load, so the extraction vocabulary
/// and the query lexicon cannot drift apart.
/// </para>
/// <para>
/// Canonical names are written in stored <c>predicate_key</c> form - lowercase, separators folded to
/// single spaces - because resolution that produced keys the graph cannot match would be worthless.
/// </para>
/// <para>
/// <b>Grounded in measurement, not intuition.</b> The canonical set covers the predicates actually
/// observed in an extracted graph (4,659 facts over 10 owners), including the frequent forms the
/// extractor invented outside the offered vocabulary - <c>wants</c>, <c>is interested in</c>,
/// <c>uses</c>, <c>asked about</c>, <c>requested</c>, <c>considered</c>. Inflectional variants are the
/// bulk of that tail (<c>plans</c> beside <c>planned</c>, <c>was</c> beside <c>is</c>), and they are
/// resolved here rather than by enlarging the write-side vocabulary.
/// </para>
/// <para>
/// <b>Deliberately excluded:</b> genuinely ambiguous forms. <c>got</c> could be <c>bought</c> or
/// <c>received</c>; a form claimed by two relations is dropped at load and reported, so an authoring
/// mistake is visible rather than silently resolved in table order.
/// </para>
/// <para>
/// The data itself lives in <c>relation-vocabulary.json</c>, embedded in this assembly. See the
/// README beside it for where each relation came from, under which licence, and what filtering was
/// applied — provenance ships with the artifact because it draws on schema.org and Wikidata.
/// </para>
/// </remarks>
internal static class MemoryRelationSeedTable
{
    /// <summary>
    /// Relations still resolvable at query time but no longer offered to extraction.
    /// </summary>
    /// <remarks>
    /// Retiring a relation must stop new writes without making facts already stored under it
    /// unreachable - a graph does not rewrite itself when the vocabulary changes.
    /// <para>
    /// <b>Two mechanisms, and knowing which is in use matters.</b> <i>Demotion</i> removes the key and
    /// keeps its name as a surface form of the relation it merged into, so the old facts are reached
    /// through the survivor; this is what <c>finished</c> and <c>welcomed</c> did. <i>Flagging</i>
    /// keeps the key but excludes it from the extraction vocabulary, which is what the filter over
    /// this set does. Demotion is preferred where a survivor exists, because it leaves one name for
    /// one meaning; flagging is for a relation being withdrawn with nothing to merge into.
    /// </para>
    /// </remarks>
    internal static IReadOnlySet<string> RetiredRelations { get; } =
        RelationVocabularyDocument.Load().Retired.ToHashSet(StringComparer.Ordinal);

    /// <summary>
    /// Content hash of the query lexicon, recorded in run reports.
    /// </summary>
    /// <remarks>
    /// Surface forms never enter a prompt, but they change what a question resolves to and therefore
    /// what is retrieved, so a run measured under a different table is not comparable to one measured
    /// under this one.
    /// </remarks>
    internal static string Fingerprint => MemoryVocabularyFingerprint.OfTable(Table);

    /// <summary>
    /// The reviewed relation table, loaded from the embedded JSON artifact.
    /// </summary>
    /// <remarks>
    /// Authored as JSON rather than C# so it is diffable in review, can be regenerated by the unifier,
    /// and can carry the per-relation source and licence provenance that a C# array cannot express -
    /// this vocabulary draws on schema.org and Wikidata and ships inside a package.
    /// </remarks>
    internal static IReadOnlyDictionary<string, string[]> Table { get; } =
        RelationVocabularyDocument.Load().Canonical.ToDictionary(
            entry => entry.Key,
            entry => entry.Value.SurfaceForms.Concat(entry.Value.StoredOnly)
                .Distinct(StringComparer.Ordinal).ToArray(),
            StringComparer.Ordinal);

    /// <summary>
    /// Forms that expansion may fetch but a question must never resolve to.
    /// </summary>
    internal static IReadOnlySet<string> QueryStopForms { get; } =
        RelationVocabularyDocument.Load().Canonical
            .SelectMany(entry => entry.Value.StoredOnly)
            .ToHashSet(StringComparer.Ordinal);
}
